import 'package:flutter/cupertino.dart';

const KMainColor = Color(0xFFFFC12F);
const KSecondColor = Color(0xFFFFE6AC);
const kProductName = 'productName';
const kProductPrice = 'productPrice';
const kProductDescription = 'productDescription';
const kProductLocation = 'productLocation';
const kProductCategory = 'productCategory';
const kProductsCollection = 'Products';
const KUnactiveColors = Color(0xFFC1BDB8);
const KJackets = 'jackets';
const KTshirts = 't-shirts';
const KTrousers = 'trousers';
const KShoes = 'shoes';
const KOrders = 'Orders';
const KOrderDetails = 'OrderDetails';
const KTotalPrice = 'TotalPrice';
const KAddress = 'Address';
const KQuatity = 'Quantity';
const KKeepUserLoggedIN = 'keepUserLoggedIn';
